# Builds application image and publishes to ECR
name: Build and publish workflow

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: eu-central-1
        role-to-assume: arn:aws:iam::319011007738:role/GitHubAction-AssumeRoleWithAction

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: devops-app
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      working-directory: ./test-app
